"""removed title column

Revision ID: d0e3d3a128b7
Revises: 976e82a7c830
Create Date: 2024-08-18 11:15:58.107509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e3d3a128b7'
down_revision = '976e82a7c830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
